crud/urls.py
from django.urls import path
from . import views

app_name = 'crud'

urlpatterns = [
    path('', views.home_orm, name='home'),
    path('adicionar/', views.contato_post, name='adicionar'),
    path('listar/', views.contato_get, name='listar'),
    path('atualizar/', views.contato_patch, name='atualizar')
]

home/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crud.urls'))
]

crud/models.py
from django.db import models

# Model de Agenda de Cll
class ContatoModel(models.Model):
    name = models.CharField(max_length=50)
    phone = models.CharField(max_length=11)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

crud/forms.py
from django.forms import ModelForm
from . import models

class ContatoForm(ModelForm):
    class Meta:
        model = models.ContatoModel
        fields = [
            'name',
            'phone'
        ]

crud/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest
from . import forms
from . import models

#HOME com POST
def home_orm(request: HttpRequest):
    return render(request, 'crud/html/index.html')

def contato_post(request: HttpRequest): 
    if request.method == 'POST':
        formulario = forms.ContatoForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect('crud:home')
    
    context = {
        'info': forms.ContatoForm()
    }
    return render(request, 'crud/html/adicionar.html', context)

def contato_get(request):
    context = {
        'info': models.ContatoModel.objects.all()
    }
    
    return render(request, 'crud/html/listar.html', context)

def contato_patch(request: HttpRequest):
    return render(request, 'crud/html/atualizar.html')

templates/crud/html/adicionar.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aprendizagem do ORM em Django</title>
</head>

<style>
    body{
        font-family: sans-serif;
        background-color: #909090;
    }

    h1{
        text-align: center;
    }

    form{
        position: absolute;
        left: 525px;
        top: 100px;
        width: 200px;
        display: block;
        background-color: #707070;
        padding: 10px;
    }

    button{
        background-color: rgb(13, 215, 20);
        font-size: 11pt;
    }

    a{
        background-color: red;
        color: black;
        text-decoration: none;
        border: 3px solid black;
        padding: 1px 5px 1px 5px;
        font-size: 11pt;
        display: inline-block;
        margin-right: 85px;
    }
</style>

<body>
    <h1>Adicione o contato</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{info}}<br/>
        <a href="{% url 'crud:home' %}">Voltar</a>
        <button>Enviar</button>
    </form>
</body>
</html>

templates/crud/html/atualizar.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<style>
    body{
        background-color: #909090;
        font-family: sans-serif;
    }

    h1{
        text-align: center;
    }
</style>

<body>
    <h1>Edite o contato!</h1>
</body>
</html>

templates/crud/html/index.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post</title>
</head>

<style>
    body{
        background-color: #909090;
        font-family: sans-serif;
    }
    div#ORM{
        display: block;
        background-color: black;
        width: 470px;
        position: absolute;
        left: 400px;
        top: 150px;
        padding: 10px;
    }

    a{
        color: white;
        font-size: 20pt;
        text-decoration: none;
        padding: 5px
    }

    a:hover{
        text-decoration: underline;
    }

    h1{
        text-align: center;
    }
</style>

<body>
        <h1>Escolha a opção!</h1>
    <div id="ORM">
        <a href="{% url 'crud:adicionar' %}">Adicionar</a>
        <a href="{% url 'crud:listar' %}">Listar</a>
        <a href="{% url 'crud:atualizar' %}">Atualizar</a>
        <a href="">Remover</a>
    </div>
</body>
</html>

templates/crud/html/listar.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listar</title>
</head>

<style>
    body{
        background-color: #909090;
        font-family: sans-serif;
    }

    h1{
        font-size: 12;
        text-align: center;
    }

    table{
        background-color: white;
        position: absolute;
        left: 430px;
        top: 200px;
        font-size: 20px;
    }

    a{
        position: absolute;
        right: 360px;
        top: 270px;
        padding: 3px 10px 3px 10px;
        font-size: 15pt;
        background-color: red;
        border: 3px solid black;
        color: white;
        text-decoration: none;
    }

    a:hover{
        text-decoration: underline;
    }

    table{
        background-color: white;
        color: black;
        position: absolute;
        left: 430px;
        top: 150px;
        font-size: 20px;
    }
</style>

<body>
    <h1>Contatos salvos!</h1>
    <table border="5">
        <thead>
            <th>Id</th>
            <th>Nome</th>
            <th>Celular</th>
            <th>Data de criação</th>
        </thead>

        <tbody>
            {% for ctt in info %}
            <tr>
                <td>{{ctt.id}}</td>
                <td>{{ ctt.name }}</td>
                <td>{{ ctt.phone }}</td>
                <td>{{ ctt.date_created }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'crud:home' %}">Voltar</a>
</body>
</html>